### ISSUE TITLE
**Front end **

### ISSUE THREAD

**Issue by mandywl** [mandywl/project1-knowledge-hub#1]
- Banner image
- Search field
- Image div
- Wikipedia div
- Twitter div

**Comment by joneill-bootcamp** [comment]
I will start on this tomorrow

**Comment by joneill-bootcamp** [comment]
Hi All,

Front end has had a few updates this evening and looks fine in a desktop browser, however we've got some issues when we look at this page in responsive design mode in FireFox.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/59762660/76678577-4d05ab00-662d-11ea-8a59-01d250fe869b.png">

I'll work on this tomorrow to see if I can get the responsive requirements for tablets/mobiles correctly proportioned.

**Comment by joneill-bootcamp** [comment]
Sorry that was a zoomed in shot, this is what I see when looking at the app in iPad mode.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/59762660/76678605-8b9b6580-662d-11ea-9e1f-2a65ca39c6ec.png">

**Comment by mohamedzakigithub** [comment]
I think this issue can be closed now.
